# Generated by Django 4.0.5 on 2022-07-23 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0003_alter_town_options_alter_town_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='town',
            options={'ordering': ['name'], 'verbose_name': 'Місто', 'verbose_name_plural': 'Міста'},
        ),
    ]
