# Generated by Django 4.0.5 on 2022-08-02 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0001_initial'),
        ('towns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва маршрута')),
                ('travel_times', models.PositiveSmallIntegerField(verbose_name='Загальний час в дорозі')),
                ('buses', models.ManyToManyField(to='buses.bus', verbose_name='Список автобусів')),
                ('from_town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_from_town_set', to='towns.town', verbose_name='З якого міста')),
                ('to_town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_to_town_set', to='towns.town', verbose_name='В яке місто')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршрути',
                'ordering': ['travel_times'],
            },
        ),
    ]
