# Generated by Django 4.0.5 on 2022-08-02 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('towns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Номер автобуса')),
                ('travel_time', models.PositiveSmallIntegerField(verbose_name='Час в дорозі')),
                ('from_town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_town_set', to='towns.town', verbose_name='З якого міста')),
                ('to_town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_town_set', to='towns.town', verbose_name='В яке місто')),
            ],
            options={
                'verbose_name': 'Автобус',
                'verbose_name_plural': 'Автобуси',
                'ordering': ['travel_time'],
            },
        ),
    ]
